### ISSUE TITLE
Error Handling in File Reading

### ISSUE THREAD

**Issue by Fahad-Ali-Khan-ca** [InderParmar/Tailor4Job#1]
Hi, The current implementation does not handle errors related to file access, such as if the file doesn't exist, if it's locked, or if it's unreadable. This can lead to unhandled exceptions, crashing the program.

**Comment by InderParmar** [comment]
This is a good insight, however my scope for release 0.1 did not include that type of error handling, I will consider it for the next release.

**Comment by InderParmar** [comment]
This is a good insight, however my scope for release 0.1 did not include that type of error handling, I will consider it for the next release.
